server:
  port: 8080

spring:
  application:
    name: deal-pipeline-backend

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/deal_pipeline_db}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: deal-pipeline-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

jwt:
  secret: ${JWT_SECRET:mysecretkeymysecretkeymysecretkey123}
  expiration: ${JWT_EXPIRATION:21600000}

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.kafka: INFO
